### ISSUE TITLE
Not all 98-100% and 0% are reported

### ISSUE THREAD

**Issue by ZombieCorn80** [versx/WhMgr-UI#40]
I would like to have all 98-100% and 0% reported!
I entered 

14/15/15
15/14/15
15/15/14
0/0/0
15/15/15

in the IV list.
but i only get 100% and 98% with 14/15/15 reported, no other 98% and also no 0%

**Comment by versx** [comment]
Should be fixed in https://github.com/versx/WhMgr-UI/releases/tag/1.6.1

**Comment by ZombieCorn80** [comment]
I tested it today with the latest and it is not fixed!
it behaves in such a way that only the first and the last combination is reported, everything in between is ignored.
please reopen and/or fix it ;-)

**Comment by versx** [comment]
Thanks, I'll try reproducing and pushing a fix hopefully later today.

**Comment by versx** [comment]
@ZombieCorn80 Should be fixed now in: https://github.com/versx/WhMgr/pull/156
